# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{cuke_salad}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["RiverGlide"]
  s.date = %q{2011-04-14}
  s.description = %q{CukeSalad allows you to focus on the task at hand - expressing examples, the roles involved in those examples and what those roles can do with the product under development.}
  s.email = %q{talktous@riverglide.com}
  s.extra_rdoc_files = [
    "README.md"
  ]
  s.files = [
    ".rspec",
    "Examples/Calculator/cucumber.yml",
    "Examples/Calculator/features/LOOK_MA_NO_STEP_DEFS.txt",
    "Examples/Calculator/features/a_place_to_start.feature",
    "Examples/Calculator/features/addition.feature",
    "Examples/Calculator/features/complex_calculations.feature",
    "Examples/Calculator/features/lib/alternative/roles/calculating_web_user.rb",
    "Examples/Calculator/features/lib/default/roles/calculating_individual.rb",
    "Examples/Calculator/features/lib/default/tasks/add.rb",
    "Examples/Calculator/features/lib/default/tasks/calculate.rb",
    "Examples/Calculator/features/lib/default/tasks/calculations.rb",
    "Examples/Calculator/features/lib/default/tasks/see_the_answer.rb",
    "Examples/Calculator/features/lib/default/tasks/subtract.rb",
    "Examples/Calculator/features/lib/default/tasks/switch_on_the_calculator.rb",
    "Examples/Calculator/features/subtraction.feature",
    "Examples/Calculator/features/support/env.rb",
    "Examples/Calculator/features/typical_workflow.feature",
    "Examples/Calculator/lib/calculator.rb",
    "Examples/Calculator/lib/config.ru",
    "Examples/Calculator/lib/web_calculator.rb",
    "Examples/Calculator/spec/calculator_spec.rb",
    "Examples/Calculator/spec/web_calculator_spec.rb",
    "Gemfile",
    "Gemfile.lock",
    "README.md",
    "cucumber.yml",
    "features/a_new_cuke_salad_project.feature",
    "features/define_a_role.feature",
    "features/define_a_task.feature",
    "features/lib/roles/step_free_cuker.rb",
    "features/lib/tasks/create_a_file.rb",
    "features/lib/tasks/create_a_new_cuke_salad_project.rb",
    "features/lib/tasks/create_a_role.rb",
    "features/lib/tasks/create_a_task.rb",
    "features/lib/tasks/create_directories.rb",
    "features/lib/tasks/not_create_a_role.rb",
    "features/lib/tasks/not_create_a_task.rb",
    "features/lib/tasks/run.rb",
    "features/lib/tasks/run_a_scenario.rb",
    "features/lib/tasks/see_a_reply.rb",
    "features/lib/tasks/see_the_step_has.rb",
    "features/support/env.rb",
    "lib/actor.rb",
    "lib/codify/const_name.rb",
    "lib/cuke_salad.rb",
    "lib/director.rb",
    "lib/specifics.rb",
    "lib/task_author.rb",
    "spec/actor_spec.rb",
    "spec/codify/as_const_name_spec.rb",
    "spec/director_spec.rb",
    "spec/spec_helper.rb",
    "spec/specifics_spec.rb",
    "spec/task_author_spec.rb"
  ]
  s.homepage = %q{https://github.com/RiverGlide/CukeSalad}
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.5.2}
  s.summary = %q{Step free cucumber}
  s.test_files = [
    "examples/Calculator/features/lib/alternative/roles/calculating_web_user.rb",
    "examples/Calculator/features/lib/default/roles/calculating_individual.rb",
    "examples/Calculator/features/lib/default/tasks/add.rb",
    "examples/Calculator/features/lib/default/tasks/calculate.rb",
    "examples/Calculator/features/lib/default/tasks/calculations.rb",
    "examples/Calculator/features/lib/default/tasks/see_the_answer.rb",
    "examples/Calculator/features/lib/default/tasks/subtract.rb",
    "examples/Calculator/features/lib/default/tasks/switch_on_the_calculator.rb",
    "examples/Calculator/features/support/env.rb",
    "examples/Calculator/lib/calculator.rb",
    "examples/Calculator/lib/web_calculator.rb",
    "examples/Calculator/spec/calculator_spec.rb",
    "examples/Calculator/spec/web_calculator_spec.rb",
    "spec/actor_spec.rb",
    "spec/codify/as_const_name_spec.rb",
    "spec/director_spec.rb",
    "spec/spec_helper.rb",
    "spec/specifics_spec.rb",
    "spec/task_author_spec.rb"
  ]

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<cucumber>, ["= 0.10.0"])
      s.add_runtime_dependency(%q<rspec>, ["= 2.5.0"])
      s.add_runtime_dependency(%q<capybara>, ["= 0.4.1.2"])
      s.add_runtime_dependency(%q<sinatra>, ["= 1.2.0"])
      s.add_runtime_dependency(%q<aruba>, ["= 0.3.5"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.5.2"])
    else
      s.add_dependency(%q<cucumber>, ["= 0.10.0"])
      s.add_dependency(%q<rspec>, ["= 2.5.0"])
      s.add_dependency(%q<capybara>, ["= 0.4.1.2"])
      s.add_dependency(%q<sinatra>, ["= 1.2.0"])
      s.add_dependency(%q<aruba>, ["= 0.3.5"])
      s.add_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.5.2"])
    end
  else
    s.add_dependency(%q<cucumber>, ["= 0.10.0"])
    s.add_dependency(%q<rspec>, ["= 2.5.0"])
    s.add_dependency(%q<capybara>, ["= 0.4.1.2"])
    s.add_dependency(%q<sinatra>, ["= 1.2.0"])
    s.add_dependency(%q<aruba>, ["= 0.3.5"])
    s.add_dependency(%q<bundler>, ["~> 1.0.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.5.2"])
  end
end

