require 'rubygems'
require 'bundler'

namespace :check do
  require 'rspec/core'
  require 'rspec/core/rake_task'
  RSpec::Core::RakeTask.new(:design) do |spec|
    spec.pattern = FileList['spec/**/*_spec.rb']
    spec.rspec_opts = "-cfd"
  end

  require 'cucumber/rake/task'
  Cucumber::Rake::Task.new(:features)

  namespace :features do
    Cucumber::Rake::Task.new(:back_door) do |wip|
      wip.cucumber_opts = "-p back_door"
    end

    Cucumber::Rake::Task.new(:side_door) do |wip|
      wip.cucumber_opts = "-p side_door"
    end

    Cucumber::Rake::Task.new(:front_door) do |wip|
      wip.cucumber_opts = "-p front_door"
    end
  end

  desc "Check absolutely everything!"
  task :everything => [
    'check:design', 
    'check:features:back_door',
    'check:features:side_door', 
    'check:features:front_door'
  ]
end

desc "Check design and features"
task :default => [
  'check:design', 
  'check:features:side_door'
]
